### ISSUE TITLE
Add new properties to "counter" in stories collection

### ISSUE THREAD

**Issue by afirdousi** [Eventapture/eventapture-mongo#2]
Please add the following 2 properties to the "counter" node in each stories document.

hide:0,
report:0

so for example for one story in the stories collection the counter will look like:

```
"counter" : {
        "impression" : 2136,
        "share" : 234,
        "textComment" : 3,
        "audioComment" : 0,
        "videoComment" : 1,
        "hide":0,
        "report":0,
        "reaction" : {
            "like" : 457,
            "dislike" : 233,
            "hate" : 27,
            "love" : 399,
            "sad" : 245,
            "happy" : 298,
            "funny" : 150
        }
    }
```

**Comment by srinathsj92** [comment]
Added the 2 new properties 'hide':0 and 'report':0 to the counter sub-document in all documents.

Removed the 'hide' and 'report' object arrays which we had added before as a placeholder.
